### ISSUE TITLE
index_updates testing

### ISSUE THREAD

**Issue by sdarwin** [CPPAlliance/paperbot#4]
Hi @JankoDedic ,
Good progress on the index updates!
Here is some feedback. Running in an Nginx/Passenger environment, the very first request gets lost. The server is lazy about loading the app until a web request comes in. Then it gets a web request and launches the app.  The bot starts running and simultaneously downloads the index.json and also gives an error about that first search like "Error occurred: TypeError: Cannot read property 'P1020R0' of undefined", probably because the index.json download hasn't finished yet. The second request will be fine. Even if the app were more synchronous and waited for the download to complete before doing the search there would be a delay on the first request.

A solution to avoid either a delay or error is to initially load index.json from the local filesystem, like before. Start only with the local file.  Web updates are done in the background on a timer, but not initially on launch.
More potential optimization: after a web update, save it locally to index.cache.json.  When an instance of the app starts, it tries to re-use index.cache.json.

**Comment by JankoDedic** [comment]
Hi Sam, thanks for the feedback.

Now I recognize that it was a mistake not to ensure that the index is populated before processing any web requests. That will be fixed so that no requests are lost.

I did consider caching the index in the filesystem and downloading a new one only if the file is stale, but that's not possible in an environment without persistent storage (like Heroku). However, the downsides to unconditionally downloading on startup are (1) slight delay on the first request in some environments (as you've mentioned) and (2) the app can happen to start at the moment when the remote index is unavailable and remain empty-handed.

I don't think that these downsides are particularly serious, but let me know if you think otherwise and how we would go about it.

**Comment by sdarwin** [comment]
That's an interesting point about Heroku.  Ideally the code can be optimized to perform well on many platforms, including both ephemeral and persistent storage, so an _optional_ local cache file could still be a possibility.

This update should fix delays/errors:   https://github.com/CPPAlliance/paperbot/pull/5   

Part of it was that JSON.parse() needed to be there.

**Comment by JankoDedic** [comment]
@sdarwin You can check the latest `index_updates2` branch that I've pushed. I think it provides a more robust solution.

It will initialize the index with the cached file (if that file exists and is not stale). Otherwise, it will download the file. Caching will obviously only work on servers with persistent storage, but it doesn't really affect other environments.

Even if the app is loaded lazily on a web request, the only correct thing to do is to load the up-to-date index first (be it by reading the cached file or downloading it).

**Comment by sdarwin** [comment]
Those changes make sense. Good idea.
